# - name: Set Node.js version
#   set_fact:
#     nodejs_version: "16.15"

# - name: Installing NodeJS
#   become: yes
#   package:
#     name: nodejs
#     state: present
#     update_cache: yes

# - name: Installing npm (Node Package Manager)
#   become: yes
#   package:
#     name: npm
#     state: present
#     update_cache: yes

# - name: Set the desired NodeJS version
#   become: yes
#   command: "npm install -g n && n {{ nodejs_version }}"
#   args:
#     creates: "/usr/local/bin/node{{ nodejs_version[0] }}"

# - name: Update the default node version
#   become: yes
#   command: "npm use node{{ nodejs_version[0] }} default"


# - name: Set Node.js version
#   set_fact:
#     nodejs_version: "16.15.1"

# - name: Add NodeJS repository
#   apt_repository:
#     repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
#     state: present

# - name: Add NodeJS repository key
#   apt_key:
#     url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
#     state: present

# - name: Install NodeJS package
#   package:
#     name: nodejs
#     state: present
- name: "Add nodejs apt key"
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: "Add nodejs 13.x ppa for apt repo"
  apt_repository:
    repo: deb https://deb.nodesource.com/node_13.x bionic main
    update_cache: yes
    
- name: "Install nodejs"
  apt:
    update_cache: yes
    name: nodejs
    state: present